# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific environment
PATH="$HOME/.local/bin:$HOME/bin:$PATH"
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

ulimit -s unlimited
ulimit -n 4096
source /home/alejandro/LIBRARIES/bashrc.opt-ifort_2021

# Variables WRF-CMAQ and WRF-Chem
export BIN="Linux2_x86_64ifort"
export DIR="/opt/comp_ifort_2021"
#export CC=icc
#export CXX=icpc
#export FC=ifort
#export FCFLAGS=-m64
#export F77=ifort
#export FFLAGS=-m64
#export HDF5=$DIR/hdf5
#export JASPERINC="$DIR/grib2/include"
#export JASPERLIB="$DIR/grib2/lib"
#export LDFLAGS="-L$DIR/grib2/lib"
#export CPPFLAGS="-I$DIR/grib2/include"
export PATH="$DIR/netcdf/bin:$DIR/mpich/bin:$PATH"
export NETCDF_DIR="$DIR/netcdf"
export NETCDF=${DIR}/netcdf
export LD_LIBRARY_PATH=${DIR}/netcdf/lib:$LD_LIBRARY_PATH

export WRF_EM_CORE=1                  # WRF-Chem only works with ARW
export WRF_NMM_CORE=0
#export WRF_CHEM=1                       # To install with Chemistry
export WRFIO_NCD_LARGE_FILE_SUPPORT=1
#export WRF_KPP=1                         # To install with KPP
export YACC='/usr/bin/yacc -d'
export FLEX_LIB_DIR="/usr/lib64"
export MALLOC_CHECK_=0

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/alejandro/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/alejandro/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/alejandro/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/alejandro/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

#conda config --set auto_activate false
conda deactivate

